FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.8

RUN bin/elasticsearch-plugin install --batch https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/6.8.8.0/prometheus-exporter-6.8.8.0.zip
